learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from django.urls import path

app_name = 'basic_app' #For template tagging in relative_urls_template.html, the name assigned here gets used.

urlpatterns= [
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from basic_app import views

urlpatterns = [

    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    dict = {'name':'Summa Lumma', 'number':7}
    return render(request,'basic_app/index.html', dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_urls_template.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="#">Brand</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}"</a>Admin</li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:relative' %}">relative_url_template</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body-block %}
      <!-- Anything outside of this will be inherited when extended -->
      {% endblock %}

    </div>


  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

  {% block body-block %}
    <h1>Welcome to Index page</h1>
    <h1>{{ name|cut:'Summa'}}</h1> <!-- Use pipe operator and then add template filter -->
    <h1>{{ number|add:"88" }}</h1>
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

  {% block body-block %}
    <h1>Welcome to Other page</h1>
    <h1>This is an example of template inheritance </h1>
  {% endblock %}

learning_templates/templates/basic_app/relative_urls_template.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> Welcome to Relative url template page </title>
  </head>

  <body>
        <h1>Welcome to Relative url template page</h1>
          <a href="{% url 'basic_app:other' %}"> Other HTML </a> <!--  Referencing app_name created in urls.py(basic_app)   -->
      <br><a href="{% url 'admin:index' %}"> Admin</a>
      <br><a href="{% url 'index' %}"> Index</a>
  </body>
</html>